= Hero
:hp-tags: personal

My Facebook this morning brought to my attention http://www.hitfix.com/news/carrie-fisher-just-scorched-good-morning-america-and-youre-not-worthy[this amazing and wonderful interview with Carrie Fisher and her dog Gary.]

Carrie Fisher is something of a hero of mine. And not because of Star Wars, massive fan that I am, but from  interviews like this one, and especially when I first saw her talk with Stephen Fry in his amazing "The Secret Life of the Manic Depressive".

Years of dealing with drug abuse, Hollywood sexism, and a serious case of bipolar disorder, and she takes it with humor and wit and tenacity and it gives me hope the rest of us can do the same. 

I have, as I've increasingly made no attempts to hide, a whole fucking raft of mental problems. The clinical depression I've talked about at some length, with its mood swings, lack of motivation, self-doubt, and even suicidal thoughts, kept at bay only by a mortal fear of death and pain. For this I'm on a daily regimen of two moclobemide a day to keep it from being even worse than what I deal with on the stuff. The doctors waffle back and forth on my official diagnosis, whether it's chronic or moderate or mild or whatever, but the truth is that I've been dealing with depression since I was a child, and may very well always deal with it. 

What I don't much, if ever, talk about is the social issues. I had an extremely isolated and sheltered childhood, thanks to growing up first an only child and home schooled, then moved around damn near every other year, and facing bullying for much of my schooling, and the result is that I'm frankly kind of clueless about how to even handle myself in a lot of social functions and interactions, and especially romantic ones. I fake it well in the right circumstances but sometimes when you see me being all gregarious or running at the mouth, that's just because I don't know what else to do. I'm a man of words and so it's sometimes the only tool in the box. Yet other times I'm so terrified of saying or doing the wrong thing, that often I simply don't act at all, and sit in the corner in silence until I can go home. 

When I moved to Finland I also developed severe anxiety, owing to largely the combination of culture shock and psychological abuse. The first time it happened I didn't even know what was happening, I just blacked out in the middle of a conversation and stopped even being able to put a train of thought together. For the most part it's under control now, but I still have a bottle of oxazepam in my house in case of emergencies, and I still get irrationally nervous in certain social situations especially if I have to use Finnish. 

I have an attention disorder. I don't know which, because it's never been officially diagnosed, but it runs in the family, and the symptoms are all there. I have a hard time focusing on anything for too long a space of time, save for those times when I become so hyperfocused on one thing I ignore or neglect everything around me to sometimes pathological extent. 

And so, with all of this to deal with, for a good 10 to 20 years of my life, I just dealt with it by lopping off parts of my personality. I couldn't deal with fear so I conditioned myself not to think of anything scary. I never had much joy to begin with, but what I did I came to treat with suspicion. I couldn't focus anything so I just gave up on any hope of achieving anything, and even on many of the things I used to love, like films and games. I didn't know how to deal with social situations, so I mostly just stopped having friends, and even now have a bad habit of falling out of touch with anyone I don't see regularly. Love, year on year, just lead to one broken heart after another, so I gave up on that too. All I had left was a life of emotional deadness punctuated only by the occasional angry outburst. 

But after over a decade living like a hermit and longer still living under the thumb of all that mess, I'm just fucking sick of it. I mean it. The very idea now that I might let any of it keep me from what I really want in life fills me with actual anger. If I've learned anything from spending my life dealing with mental illness it's that sometimes the greatest threat is how much power you give it over you. 

I set out for my standup debut to write a set about depression, because I wanted to strip it of that power. To make a fucking mockery of it. To educate, to deprive it of its mystique, of its stigma, and of the hopelessness it can set about your mind. 

Even as I struggle with it daily, I refuse to be constrained by it, or to let it tell me I am worthless or unworthy because of it. I want to live. I want to love. I want to come out of the cave. 

And seeing Carrie up there on the screen gives me hope that another 20 years on I still can be there, fighting on. 