= How to do things
:hp-tags: personal

A thread on HN asks, https://news.ycombinator.com/item?id=9936544["Why do you want to achieve something?"] This https://news.ycombinator.com/item?id=9939147[particular answer] struck a chord:

____
Honestly, it's the growing realization that despite all of my efforts, I haven't done anything worth feeling proud of. To me that feels like I've lived a waste of a life.

As you can tell, this is an ineffective strategy for motivation.
____


When I was a child, my parents and I once went down to see a guest preacher at the local church down in the canyon. It was the concluding event of a "vacation bible camp" I'd been attending on my parents'  wishes over the summer. I don't really remember the content of the speech he gave, other than that the speaker was fond of audience participation, and at several points had called upon random members of the audience.

I was one of them.

That day, I had chosen to wear to church the jersey of the Chicago Cubs, the famously losing baseball team, who had not at that time won a World Series in something nearly like a century. I wasn't really a fan or anything, I didn't even like baseball, but someone had given it to me, and I liked wearing it because it was comfortable and cool in the summer time.

The preacher had evidently noticed the shirt, however, and at one point in his sermon chose to punctuate his point by singling me out of the crowd based entirely on my choice of clothing. He told me he felt sorry for anyone who was a Cubs fan, but admired my decision to stick with a losing team. For taking part as living prop to his point, or perhaps just for being a good sport and saying little of anything to interrupt it, he gave me a little plastic dinosaur egg, inside which I would later discover was some mediocre candy and a tiny rubberized plastic velociraptor. 

