= Fuck you, I'm great
:hp-tags: personal

++++
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Hey new dev - think you&#39;re dumb? I struggled for 2 hours yesterday because I forgot how a single HTML tag works. We all make mistakes. ❤</p>&mdash; 10x Pro Grammar (@kerrizor) <a href="https://twitter.com/kerrizor/status/646699976911814656">September 23, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

When I first got back into programming, I was pleasantly surprised to discover that after all these years I still rather enjoyed it. When I then discovered, and finally understood, Lisp and functional programming, it blew my mind. It felt like magic; here was a way of doing programming that had actually thought hard about how to abstract away much of the tedium, and how to compose those abstractions in powerful ways that made the old days of structured QBasic and even modern Python feel like going back to the stone ages. 

At one point, after listening to a lot of Neil Gaiman and feeling the high of the newbie functional programmer who feels like he's working some kind of sorcery whenever he writes a curried function, I'd even started a weird piece of urban fantasy fiction about forgotten gods who've learned the language of the universe itself, hiding out as Lisp gurus in unassuming office blocks.

But the days of "programming is magic" seem ever numbered for most programmers, myself not excluded. Over time, programming takes on a different, darker hue. Oh for sure there are still moments where you find some clever bit that someone else has coded, or come up with some clever function of your own, that the old wizardry shines through. But then you have one of those days where you fight CSS bugs for an entire work day, or have to Google a function you could swear you just used yesterday, or have a bit of code refuse to work despite being identical to at least a dozen other bits of code in the same file.