= Lost
:hp-tags: personal

I want a burrito.

I have lived in Finland for two years, and sometimes, even often, I still crave a burrito. And not just any burrito, but the unique blend of cheese, greasy meat, and too-runny, lard-cooked refried beans you can acquire at Mexican-American taquerias almost anywhere in Western United States. 

I can of course make burritos. I learned how to make a mighty fine burrito from my father when I was a child, who himself improvised what would become the family burrito recipe after having first had the product of a particularly good such taqueria in Madras, Oregon while working for the wood products company that would employ him until he was stricken with esophageal cancer caused by decades of untreated acid reflux disease.

I even, during a period of significant poverty during which I had inherited a barrel full of pinto beans from the kitchen where I was employed, had learned how to make refried beans from scratch. 

And yet, I was never able to truly reproduce that taqueria experience, nor am I here in Finland fully able to reproduce the hot pork sausage which was the cornerstone of the family burrito recipe either. In fact, it was only recently that I was easily able to acquire even a suitable cheese for a good burrito, thanks to the Fazer Company putting out a line of pre-grated cheddar and mozzarella tossed with peppers and spices, which serves as a reasonable substitute. I have done the best I can here, but even finding the right beans is difficult in Finland. At home I have more often of late stuck with Tex-Mex styled tacos and fajitas, owing to the greater easy of reproducing the experience.

I just want to go down to a local burrito joint and buy one of those big burritos the size of my head and devour it. And as long as I am here, I cannot.

***

I bought a packet of cigarettes today. Lucky Strike Reds, the local version of an old favorite.

It is the first such pack I've purchased in some time, not since a particularly rough patch in the summer of last year, which ended after only a couple of months at the most. Part of my decision to terminate their use was because my wife was quite upset at the prospect of my taking on the habit again, but partly it was because they just aren't the same here. 

I was initially elated to discover that they had many of my most favorite brands here, even my beloved Chesterfield cigarettes, a brand long dead in America, and which I had not smoked in maybe 15 years. The last place I knew of to find them was a particular Safeway store in Redmond, Oregon, where I'm told they were pretty much only bought by a handful of retirees.

Sadly, I would be disappointed to discover that despite the brand names, they were not at all the same recipes and were more or less unidentifiable as any cigarette I had ever smoked abroad. It turns out, for one thing, that there are laws in Finland regarding the manufacture of cigarettes. Their nicotine content is tightly controlled and broken into categories, and they're required to be impregnated with chemicals that make them self-extinguishing, so that Finland's great forests aren't set ablaze by stray butts like so many of America's are. The result is that almost every cigarette I have ever smoked in Finland has all tasted and smoked exactly the same.

***

Outside the kiosk where I purchased my cigarettes, there was a young woman there panhandling for change. She was dressed in punk attire, with a ripped jean jacket covered in patches, tattered black stockings, and had a shock of blue hair. She was spread out on some bit of cloth, and holding a cardboard sign asking for money for some purpose which I was unable to translate.

As I passed her going in, she smiled at me and chirped a polite request for attention in Finnish which I did not fully understand. She was quite cheery for a panhandler, and rather lovely too, and I theorized that she was probably a musician of some kind. 

So, when I came out of the kiosk and had lit my first cigarette in at least a year, I went over and dropped to fifty-cent pieces into her cup. She had been joined by another young woman, who both now thanked me merrily as I went on my way. 

When my bus would pass back by there some 5 minutes later, they were gone, and a man with a mohawk had taken their place.

And life goes on.

***

In the early days of my time here, my wife would criticize me for my tendency to go on and on about the differences here, and about the things I missed from back in the United States. At times it darn near boiled her blood: she would get angry, appalled at what seemed to her to be by omission slighting the products of her homeland in my complaints. 

You're here now, she would remind me, and tell me that I should learn to accept what's in front of me. That I was in Finland and I should expect what Finland has to offer, not to torture myself over what I can't have. 

My wife and I are separating now, because I could not accept all of what she was either. 


It is not that I did not try to do so. I tried so long and so hard that it made me a wreck of self-doubt, and in turn, the fact that I so obviously was struggling with that doubt made her a wreck of self-doubt too. 

When I came here, I came here pursuing a dream. I had, based only on our rapt and endless conversations and a handful of pictures, fallen madly in love with a woman who I almost at once decided to run off a foreign land to meet, to be with her and only her for the rest of my life. She was warm, and kind, and forgiving, and sang like no songbird on earth, and she would be my wife, there could be nothing else for it.

So confident was I in this impossible dream, that I would produce one of the hardest creative projects of my life just to pay for me to buy as close to a one-way ticket as I could get. I was genuinely annoyed that it turns out the airlines won't even let you buy a one-way ticket overseas, so feeling so self-assured that I would have no need of the return ticket, I scheduled my return for three months away: the maximum visa period. 

I wrote and wrote and waited and waited until the day I would board that plane. I had already dispossessed myself of much of my belongings when I had gone to university, but now I would leave behind even much of these, taking only a suitcase full of clothes and the stuffed bear I had owned since infancy, and shipping my computer in bits by post to arrive sometime after I got there.

And then, the day came. I packed my bags, took a bus first to Olympia and then by shuttle to the Seattle-Tacoma Airport, where I would board a plane that would take me away from the United States, possibly forever. The flight was long, some thirty hours of ever so slightly uncomfortable economy class during which my ears never popped, and with a transition in Amsterdam which I would nearly miss and would cost me access to my luggage for several weeks, but I made it.

I arrived at Helsinki Airport. After some waiting around wondering when my bags would come, I inquired at the desk what had become of them, only to be told it had been left behind. All of my possessions save a tiny carry-on bag were now still somewhere in Amsterdam. They gave me a tiny travel kit and said my bags would be along and they would notify me when they were available. 

And then I walked out through the security gate and proceeded to commit one of the worst of my many crimes: I was disappointed. 

My dream wasn't a dream, just a person. It was the lowest and most shallow moment of my life, but I realized almost immediately that she did not look like who I had imagined from those handfuls of photographs, and I was disappointed. 

And she knew it, immediately. She even asked me about it later that evening, and I just hedged and lied and said she was taller than I'd expected and I'd been surprised. I would continue to hedge and lie in moments like that for two years. I was scared, confused, and I didn't want to hurt anyone, so I lied. It would become the rotten worm at the core of our marriage, turning me distant and her alternately resentful and insecure.

I tried to remind myself of who I fell in love with, that it was still her after all, still the same person I'd talked to through all those late nights. Still the same beautiful eyes, the same warm smile. But the smiles got fewer and farther between over the years. Her doubts and my neglect turned to harshness, impatience, and fighting. Every fight seemed worse than the last, and with every fight, it just got harder and harder to remember what it was that I loved about her. I was also terrified even still to find myself alone again, but what would happen to me in this strange land without her or the "family member" status that being married gave me. In time this fear would turn into full blown anxiety, the panic attacks from which would wind up putting me in the hospital at least twice, and leave me constantly scared of my own shadow. 

The panic then blew up again when I first came to Finnish school, and as I dove into trying to speed-learn my way into some kind of employable level of programming skill. This panic and stress over the first thing I'd really done to contribute to our welfare in two years lead to even more and uglier fights, and the worsening of her mental state as well. The endless alternation between verbal combat and isolation wore me down until I simply went numb, trying only to get through each day without setting off another battle, and having seemed to lose any sense of what I was doing here other than obligation.

Finally, my neglect and growing coldness could not be ignored, and she asked me to be honest. So I was. 

I broke her heart for a second time, this time by telling her the truth. 