= Fuck you, I'm great
:hp-tags: personal

++++
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Hey new dev - think you&#39;re dumb? I struggled for 2 hours yesterday because I forgot how a single HTML tag works. We all make mistakes. ❤</p>&mdash; 10x Pro Grammar (@kerrizor) <a href="https://twitter.com/kerrizor/status/646699976911814656">September 23, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

When I first got back into programming, I was pleasantly surprised to discover that after all these years I still rather enjoyed it. When I then discovered, and finally understood, Lisp and functional programming, it blew my mind. It felt like magic; here was a way of doing programming that had actually thought hard about how to abstract away much of the tedium, and how to compose those abstractions in powerful ways that made the old days of structured QBasic and even modern Python feel like going back to the stone ages. 

At one point, after listening to a lot of Neil Gaiman and feeling the high of the newbie functional programmer who feels like he's working some kind of sorcery whenever he writes a curried function, I'd even started a weird piece of urban fantasy fiction about forgotten gods who've learned the language of the universe itself, hiding out as Lisp gurus in unassuming office blocks.

But the days of "programming is magic" seem ever numbered for most programmers, myself not excluded. Over time, programming takes on a different, darker hue. Oh for sure there are still moments where you find some clever bit that someone else has coded, or come up with some clever function of your own, that the old wizardry shines through. But then you have one of those days where you fight CSS bugs for an entire work day, or have to Google a function you could swear you just used yesterday, or have a bit of code refuse to work despite being identical to at least a dozen other bits of code in the same file. 

That's when the lights start to flicker.

Perhaps the more accurate phrase is "programming is gaslighting."

***

This pattern of conflict continues in my language studies. Finnish is a language packed to the gills with syntax, and teachers who teach it blindly with little concern as to the semantics, and often no knowledge of how to even explain it. In my early studies at first it seemed like I was indeed learning quite quickly, but soon found my actualy comprehension of Finnish, especially in the real world, was far slower to catch up with. Time and again in my language studies I am met with patronizing praise from teacher after teacher for how well I'm doing, when all the while I barely comprehend the most basic conversations in Finnish.

In Finland, in order to apply for full citizenship, you must take what a language proficiency test. Normally this test costs upwards of 130€, but if you are in certain language courses and your teacher is sufficiently confident in your ability to pass it, you can apply to take it through your course for free. 

A few weeks ago, my teacher handed me that application form.

I don't even understand the practice materials for the proficiency test. My chances of actually passing this test by my estimation are just this side of nil. I couldn't even pass all the sections of the test for the "basic" half of this course. 

And then today, we spent half the class making children's building blocks out of matchsticks and paper. 

I don't want to be a kid again. Stop making me feel like one.

***

I am fast approaching the two-month anniversary of my divorce. 

My ex-wife often called me a child, among other things. 

For two years of my life I was endlessly degraded as untrustworthy and incompetent over the slightest mistakes. If I remembered to do a thing every day for two months, it would be the day I forgot that the fireworks would explode and I would be treated to a tirade about my unreliability and even unsuitability as a spouse. Everything I had ever done wrong would be dredged up again as further proof of my inability to do right when it was needed, even if only hours before some act of kindness or even simple competence had been met with glowing praise.

If I dared defend myself, which I was prone, perhaps foolishly, to do in such instances, the argument would escalate until the threats came out. She would threaten me with divorce, knowing full well what a situation that would put me in as an immigrant.

When the end finally came, the divorce papers filed, she found other things to throw at me. She called me ungrateful, denied I'd ever loved her, accused me of using her. For the first time in two years of marriage, suddenly even my abilities as a lover were not off the table. Deprived of the ability to further threaten me with divorce, she instead would threaten me with homelessness, and even the police. In the last ever argument I ever had with her, she even implied she and her parents could contact the police and tell them I'd "lied" and have me deported.

Even now, writing those words, admitting those words in public, makes me shake a little with fear. 