= Lost
:hp-tags: personal

I want a burrito.

I have lived in Finland for two years, and sometimes, even often, I still crave a burrito. And not just any burrito, but the unique blend of cheese, greasy meat, and too-runny, lard-cooked refried beans you can only acquire at a Mexican-American taqueria almost anywhere in Western United States. 

I can of course make burritos. I learned how to make a mighty fine burrito from my father when I was a child, who himself improvised what would become the family burrito recipe after having first had the product of a particularly good such taqueria in Madras, Oregon while working for the wood products company that would employ him until he was stricken with esophageal cancer caused by decades of untreated acid reflux disease.

I even, during a period of significant poverty during which I had inherited a barrel full of pinto beans from the kitchen where I was employed, had learned how to make refried beans from scratch. 

And yet, I was never able to truly reproduce that taqueria experience, nor am I here in Finland fully able to reproduce the hot pork sausage which was the cornerstone of the family burrito recipe either. In fact, it was only recently that I was easily able to acquire even a suitable cheese for a good burrito, thanks to the Fazer Company putting out a line of pre-grated cheddar and mozzarella tossed with peppers and spices, which serves as a reasonable substitute. I have done the best I can here, but even finding the right beans is difficult in Finland. At home I have more often of late stuck with Tex-Mex styled tacos and fajitas, owing to the greater easy of reproducing the experience.

I just want to go down to a local burrito joint and buy one of those big burritos the size of my head and devour it. And as long as I am here, I cannot.

***