= Why I do things
:hp-tags: personal

A thread on HN asks, https://news.ycombinator.com/item?id=9936544["Why do you want to achieve something?"] This https://news.ycombinator.com/item?id=9939147[particular answer] struck a chord:

____
Honestly, it's the growing realization that despite all of my efforts, I haven't done anything worth feeling proud of. To me that feels like I've lived a waste of a life.

As you can tell, this is an ineffective strategy for motivation.
____


When I was younger, I had big dreams. Very big dreams. I wanted to be the next great multimedia mogul, with fingers in everything: computer hardware, software, video games, movies, comics, RPGs, and on and on. I would fill notebooks for design ideas for what became a sea of white whales, from a postapocalyptic RPG that was to be _magnum opus_ on which an entire franchise would be built, to plans and specifications for a revival of the easy-to-use, plug-and-play TV computer of the 1980s, and so on.

None of these things, of course, ever happened. I had big dreams, the biggest, but somehow never felt like I knew even where to begin to learn