= Lost
:hp-tags: personal

I want a burrito.

I have lived in Finland for two years, and sometimes, even often, I still crave a burrito. And not just any burrito, but the unique blend of cheese, greasy meat, and too-runny, lard-cooked refried beans you can acquire at Mexican-American taquerias almost anywhere in Western United States. 

I can of course make burritos. I learned how to make a mighty fine burrito from my father when I was a child, who himself improvised what would become the family burrito recipe after having first had the product of a particularly good such taqueria in Madras, Oregon while working for the wood products company that would employ him until he was stricken with esophageal cancer caused by decades of untreated acid reflux disease.

I even, during a period of significant poverty during which I had inherited a barrel full of pinto beans from the kitchen where I was employed, had learned how to make refried beans from scratch. 

And yet, I was never able to truly reproduce that taqueria experience, nor am I here in Finland fully able to reproduce the hot pork sausage which was the cornerstone of the family burrito recipe either. In fact, it was only recently that I was easily able to acquire even a suitable cheese for a good burrito, thanks to the Fazer Company putting out a line of pre-grated cheddar and mozzarella tossed with peppers and spices, which serves as a reasonable substitute. I have done the best I can here, but even finding the right beans is difficult in Finland. At home I have more often of late stuck with Tex-Mex styled tacos and fajitas, owing to the greater easy of reproducing the experience.

I just want to go down to a local burrito joint and buy one of those big burritos the size of my head and devour it. And as long as I am here, I cannot.

***

I bought a packet of cigarettes today. Lucky Strike Reds, the local version of an old favorite.

It is the first such pack I've purchased in some time, not since a particularly rough patch in the summer of last year, which ended after only a couple of months at the most. Part of my decision to terminate their use was because my wife was quite upset at the prospect of my taking on the habit again, but partly it was because they just aren't the same here. 

I was initially elated to discover that they had many of my most favorite brands here, even my beloved Chesterfield cigarettes, a brand long dead in America, and which I had not smoked in maybe 15 years. The last place I knew of to find them was a particular Safeway store in Redmond, Oregon, where I'm told they were pretty much only bought by a handful of retirees.

Sadly, I would be disappointed to discover that despite the brand names, they were not at all the same recipes and were more or less unidentifiable as any cigarette I had ever smoked abroad. It turns out, for one thing, that there are laws in Finland regarding the manufacture of cigarettes. Their nicotine content is tightly controlled and broken into categories, and they're required to be impregnated with chemicals that make them self-extinguishing, so that Finland's great forests aren't set ablaze by stray butts like so many of America's are. The result is that almost every cigarette I have ever smoked in Finland has all tasted and smoked exactly the same.

***

Outside the kiosk where I purchased my cigarettes, there was a young woman there panhandling for change. She was dressed in punk attire, with a ripped jean jacket covered in patches, tattered black stockings, and had a shock of blue hair. She was spread out on some bit of cloth, and holding a cardboard sign asking for money for some purpose which I was unable to translate.

As I passed her going in, she smiled at me and chirped a polite request for attention in Finnish which I did not fully understand. She was quite cheery for a panhandler, and rather lovely too, and I theorized that she was probably a musician of some kind. 

So, when I came out of the kiosk and had lit my first cigarette in at least a year, I went over and dropped to fifty-cent pieces into her cup. She had been joined by another young woman, who both now thanked me merrily as I went on my way. 

When my bus would pass back by there some 5 minutes later, they were gone, and a man with a mohawk had taken their place.

And life goes on.

***

