= How to do things
:hp-tags: personal

A thread on HN asks, https://news.ycombinator.com/item?id=9936544["Why do you want to achieve something?"] This https://news.ycombinator.com/item?id=9939147[particular answer] struck a chord:

____
Honestly, it's the growing realization that despite all of my efforts, I haven't done anything worth feeling proud of. To me that feels like I've lived a waste of a life.

As you can tell, this is an ineffective strategy for motivation.
____


When I was a child, my parents and I once went down to see a guest preacher at the local church down in the canyon. It was the concluding event of a "vacation bible camp" I'd been attending on my parents'  wishes over the summer. I don't really remember the content of the speech he gave, other than that the speaker was fond of audience participation, and at several points had called upon random members of the audience.

I was one of them.

That day, I had chosen to wear to church the jersey of the Chicago Cubs, the famously losing baseball team, who had not at that time won a World Series in something nearly like a century. I wasn't really a fan or anything, I didn't even like baseball, but someone had given it to me, and I liked wearing it because it was comfortable and cool in the summer time.

The preacher had evidently noticed the shirt, however, and at one point in his sermon chose to punctuate his point by singling me out of the crowd based entirely on my choice of clothing. He told me he felt sorry for anyone who was a Cubs fan, but admired my decision to stick with a losing team. For taking part as living prop to his point, or perhaps just for being a good sport and saying little of anything to interrupt it, he gave me a little plastic dinosaur egg, inside which I would later discover was some mediocre candy and a tiny rubberized plastic velociraptor. 

I just liked the shirt.

***

When I was 18, and what was left of my high school education was rapidly drawing to a close, my father came to me and told me he had an opportunity at work for me. The IT department at work was looking to hire a new employee, and that I would be perfect for the job owing to the peculiar requirement that the IT department head had set on the hire.

The new boss was a man with a considerable amount of experience in the IT industry, and also who had a very particular way of doing things. Because of this, he quite specifically did not want to hire anyone who had any real work experience in the field, preferring instead a new body who would serve as a kind of apprentice. He could then train up a new employee to do exactly what he needed them to do, in the way that he needed them to do it, without having to "untrain" them from any method they might've picked up in their previous jobs.

He and my father had evidently discussed me as a serious candidate position, and felt that my hobby experience with computers would make me a perfect candidate. The job was more or less mine, all I had to do was say I wanted it, and I could be employed tomorrow. The pay was good, probably better from the start than any job I would wind up taking the rest of my life, and it came with benefits like health care and vacation which didn't seem especially important to me at the time but nowadays are worth their price alone. 

I turned it down.

I didn't want to have to stay living with my parents, out in Crooked River Ranch, which was so far away from anything like culture or human activity that for me it may as well have been the third moon of Rigel IV. Nor did I want to move to Madras, closer to where work was actually located, because it was and still is the asshole the tri-county area, essentially an entire city that had been turned into a ghetto for migrant workers from Mexico.

I said too, that I didn't think I wanted to work with computers for a living. That they were fine and fun as a hobby, but I was afraid I'd soon come not to enjoy dealing with them at all if I had to do anything with them for work. 

Sometimes I wonder if I was right ...

***

Nearly five years ago now, after reaching more or less the inescapable death of my cooking career, and being rejected by the United States Air Force on the basis of my poor credit history, I enrolled at  Central Oregon Community College in Bend, Oregon. I didn't really know what else I was going to do, so I though, well, maybe I should finally go back to school and learn how to do something that would pay me a living without having to be exchanged for a life of bone-battering toil.

College was a wonderful place. I felt like I was at home for the first time in a decade. I had incredible teachers and professors, who taught me about writing and literature and history, who gave me the chance to explore talents that had been all but neglected for the past third of my life. 

One of those professors was Cora Agatucci, an incredible old woman with a passion for film like no one I have ever met before. She was the kind of woman who would sigh dreamily at the thought of a good Truffaut shot, and her enthusiasm was almost viral. Almost no one, even the most slackoff of students, could manage to find no joy in her classrooms, and it was there that I rekindled a long neglected love of film. 

I decided, in fact, that I would make it my major, and even registered it as such with the admissions office. I made inquiries into what universities would be best for me to eventually transfer to in order to complete my degree, and learned of a promising new "cinema studies" program at the University of Oregon.

It was around this time, however, that an acquaintance of mine who worked in the film industry suggested instead that I should not waste my time with university, or even a degree. He said it wasn't necessary, and if I really wanted to get into film what I should do was just come down to California and he would help find me internships on film sets instead, where I could learn on the job.

I declined his offer. I said I wasn't really sure I wanted to live in California, and I as will still felt like I needed the qualification and credential a degree would give me. Indeed, at one point I'd more or less decided that I wanted to try and make a go of a film career without ever having to go anywhere near Los Angeles if I could help it, and in fact, harbored hopes of even studying abroad somehow instead. Maybe Vancouver, or France. 