= That flag.
:hp-tags: politics

Because this keeps coming up for some reason, this is what the POW/MIA flag is about. https://en.wikipedia.org/wiki/POW/MIA_flag

The POW/MIA Flag was created and ratified by Congress not to symbolize, as some have claimed in their outraged responses, all POWs, but rather more specifically the unaccounted-for members of the armed services missing in action after the Vietnam War.

It was initially created in support of those POWs by an organization of families of survivors, but over the intervening decades also became a political football for the right, who blamed the plight of MIAs on our early exit from the war and clung to claims that the Vietnamese still held live American captives despite evidence increasingly assigning this notion to the category of conspiracy theory, even after some photos of alleged living captives turned out to be hoaxes. This became even more obvious in 1993, when an incredibly thorough Congressional investigation by Senators John Kerry and John McCain (himself a POW in the Vietnam war) concluded:

"This disappointment does not reflect a failure of the investigation, but rather a confrontation with reality. While the Committee has some evidence suggesting the possibility a POW may have survived to the present, and while some information remains yet to be investigated, there is, at this time, no compelling evidence that proves that any American remains alive in captivity in Southeast Asia." 

http://fas.org/irp/congress/1993_rpt/pow-exec.html

Despite this, for then proposing the following year the normalization of relations with Vietnam, McCain was attacked, and even his own POW experience used against him with charges that was a "Manchurian candidate" for the Vietnamese.

Over the years it's become associated with radical groups of many stripes, both right and left, from anti-war hippies, to hanging side by side with Confederate and Nazi flags in many a wingnut's gun room, and it remains fundamentally the case that much of the persistence of the issue well into the 90s was at least a serious political issue with tinges of anti-Vietnamese, anti-Communist, and anti-government sentiment.

So while it's not strictly speaking true to ascribe to it explicitly racist motives, it's certainly had some bad company over the years, enough to make that a pretty easy mistake to make. And it's also not true at all to act like it's a purely politically innocent symbol, even leaving aside the problematic angle of our culture's persistent demand for unquestioning loyalty to the armed services and their personnel. 

So please, whether you're going to start screaming about racism, or screaming about the people screaming about racism, maybe stop to think that for once the issue might not be so black-and-white, and save all of our feeds a little senseless and ill-informed drama just this once. 