= How to do things
:hp-tags: personal

A thread on HN asks, https://news.ycombinator.com/item?id=9936544["Why do you want to achieve something?"] This https://news.ycombinator.com/item?id=9939147[particular answer] struck a chord:

____
Honestly, it's the growing realization that despite all of my efforts, I haven't done anything worth feeling proud of. To me that feels like I've lived a waste of a life.

As you can tell, this is an ineffective strategy for motivation.
____


When I was younger, I had big dreams. Very big dreams. I wanted to be the next great multimedia mogul, with fingers in everything: computer hardware, software, video games, movies, comics, RPGs, and on and on. I would fill notebooks for design ideas for what became a sea of white whales, from a postapocalyptic RPG that was to be _magnum opus_ on which an entire franchise would be built, to plans and specifications for a revival of the easy-to-use, plug-and-play TV computer of the 1980s, and so on.

None of these things, of course, ever happened. I had big dreams, the biggest, but somehow never felt like I knew even where to begin to learn how to do most of these things apart from the RPG writing, which instead fell to the twin guns of predating affordable self-publishing, and a seeming inability to ever finish any creative project I put my hands on. Until I published Heaven's Shadow, I had never finished a single writing or game design project longer than a few pages.

Instead, I more or less consistently avoided anything like success for greater than a decade. An offer to apprentice to the IT director at my father's company was declined because I didn't think I'd enjoy working with computers as more than a hobby, a conviction I'm even now not sure was wrong. College was passed on because outside of certain favored subjects I had fairly lousy grades and because I frankly was just burned out with school and didn't favor the thought of four more years of it. 

I took to couchsurfing with friends, and was basically penniless most of the time, occasionally taking work when I had to, often through connections with said friends. It was one of those friends' boyfriend who set me up with the longest job I ever had, cooking for the late Yoko's Japanese Restaurant. From there, it seemed a good enough specialty to stick to, since while it was difficult, I mostly loved cooking and at least tolerated the work more than anything else I'd tried. I still however, largely drifted from job to job, seemingly incapable of finding anything more than a kind of acceptable discomfort with my life.

By the time my father died, I was in my mid 20s