= Fuck you, I'm great
:hp-tags: personal

++++
<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">Hey new dev - think you&#39;re dumb? I struggled for 2 hours yesterday because I forgot how a single HTML tag works. We all make mistakes. ❤</p>&mdash; 10x Pro Grammar (@kerrizor) <a href="https://twitter.com/kerrizor/status/646699976911814656">September 23, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

When I first got back into programming, I was pleasantly surprised to discover that after all these years I still rather enjoyed it. When I then discovered, and finally understood, Lisp and functional programming, it blew my mind. It felt like magic; here was a way of doing programming that had actually thought hard about how to abstract away much of the tedium, and how to compose those abstractions in powerful ways that made the old days of structured QBasic, C, and even modern Python feel like going back to the stone ages. 

At one point, after listening to a lot of Neil Gaiman and feeling the high of the newbie functional programmer who feels like he's working some kind of sorcery whenever he writes a curried function, I'd even started a weird piece of urban fantasy fiction about forgotten gods who've learned the language of the universe itself, but hide out as Lisp gurus in unassuming office blocks.

But the days of "programming is magic" seem ever numbered for most programmers, myself not excluded. Over time, programming takes on a different, darker hue. Oh for sure there are still moments when the old wizardry shines through, where you find some clever bit that someone else has coded, or come up with some clever function of your own. But then you have one of those days where you fight CSS bugs for an entire work day, or have to Google a function you could swear you just used yesterday, or have a bit of code refuse to work despite being identical to at least a dozen other bits of code in the same file. 

That's when the lights start to flicker.

Perhaps the more accurate phrase is "programming is gaslighting."

***

This pattern of conflict continues in my language studies. Finnish is a language packed to the gills with syntax, and teachers who teach it blindly with little concern as to the semantics, and often no knowledge of how to even explain it. In my early studies at first it seemed like I was indeed learning quite quickly, but soon found my actualy comprehension of Finnish, especially in the real world, was far slower to catch up with. Time and again in my language studies I am met with patronizing praise from teacher after teacher for how well I'm doing, when all the while I barely comprehend the most basic conversations in Finnish.

In Finland, in order to apply for full citizenship, you must take what a language proficiency test. Normally this test costs upwards of 130€, but if you are in certain language courses and your teacher is sufficiently confident in your ability to pass it, you can apply to take it through your course for free. 

A few weeks ago, my teacher handed me that application form.

I don't even understand the practice materials for the proficiency test. My chances of actually passing this test by my estimation are just this side of nil. I couldn't even pass all the sections of the test for the "basic" half of this course. 

And then today, we spent half the class making children's building blocks out of matchsticks and paper. 

I don't want to be a kid again. 

***

My ex-wife often called me a child, among other things. 

I am fast approaching the two-month anniversary of my divorce, but for two years of my life I was endlessly degraded as untrustworthy and incompetent over the slightest mistakes. If I remembered to do a thing every day for two months, it would be the day I forgot that the fireworks would explode and I would be treated to a tirade about my unreliability and even unsuitability as a spouse. Everything I had ever done wrong would be dredged up again as further proof of my inability to do right when it was needed, even if only hours before some act of kindness or even simple competence had been met with glowing praise.

If I dared defend myself, which I was prone, perhaps foolishly, to do in such instances, the argument would escalate until the threats came out. She would threaten me with divorce, knowing full well what a situation that would put me in as an immigrant. When I asked her once after all these years if she knew what she'd been hanging over my head, she just said yes, but "it was the only way I could get you to listen."

When the end finally came, the divorce papers filed, she found other things to throw at me. She called me ungrateful, denied I'd ever loved her, accused me of using her. For the first time in two years of marriage, suddenly even my abilities as a lover were not off the table. Deprived of the ability to further threaten me with divorce, she instead would threaten me with homelessness, and even the police. In the last ever argument I ever had with her, she even implied she and her parents could contact the police and tell them I'd "lied" and have me deported.

Even now, writing those words, admitting those words in public, makes me shake a little with fear. And my heart still struggles to shake off the weight of all these sources telling me how worthless, incompetent, and unwanted I am. 

And I am goddamn sick of it.

***

I could, and indeed for some weeks now have, sit here and stew over the above. To go on believing that I am less than nothing, and depriving myself of what I most want in this world. To deride myself as a sad, fat old man, who even now has been hesitating on a million little and big steps to improving himself out of the belief that he does not and cannot deserve them. 

But you know what? That sad fat old man can go fuck himself. He's not me. He's merely an illusion, a devil's collaboration between outside and in designed to keep me in place and in check.

I am not a sad fat old man. I'm not that fat, I'm not nearly old enough to be "old," and in truth I actually haven't been all that sad lately. I realized the other day that, for the first time in longer than I can precisely determine, I have in fact had quite a few days in which I was genuinely happy. 

Instead of wallowing in self-pity, I think it's about time I put modesty aside and gave an honest self-inventory. As a society we are taught never to value you ourselves too highly in public, while at the same being endlessly shamed for our failures. To which I would like to say, "Fuck you, I'm great."

Herein then, is a short list of my talents, better natures, and life accomplishments:

* I'm a hell of a writer. And for that matter, not a bad publisher either, all things considered. I published three fucking books almost entirely on my own effort, and I still get positive reviews for Hulks and Horrors now some two years on from release.

* I am a pretty damn good singer. Despite two years of neglect, it turns out I can even still nail Chris Isaak like it was nothing, and recently I even pulled off Stairway. Even the high notes. 

* It's been a while, but quite frankly, I was a pretty good actor in school too. In two years of study I went from a barely contained mess of nerves and enthusiasm into the kind of controlled performance I never thought I'd be capable of, and I would love the chance to really work my form up again in a proper production. 

* I am a good programmer. I am not the most knowledgable nor the most experienced, but hell I've only been at this damn coding thing for a year and already I've learned and done things I'm genuinely surprised I even managed in such a short space of time. I should stop getting so overwhelmed by the complexity of big things and learn to build on things part by part. 

* I'm actually pretty funny, dammit. I sometimes wish I was "always on" the way some funny guys are, but I can crack up a room from time to time. I've felt for years like there's a funnier me in there that only sometimes gets let out the box, and I've contemplated doing standup for years. Hell I've been doing it again lately. 

* I've got a heart three sizes too big and it's killing me being alone again. For all the accusations and the recriminations, I was faithful and even cared up to the end in my marriage. It took *all of that*, all the anger and strife and threats and abuse, to make me fall out of love with my wife. I still wasn't even sure I wanted to leave yet until things truly got nasty. I can't imagine what I could be for someone who didn't insult me and threaten me with poverty and exile. I can be compassionate, attentive, and even charming when my guard is down, and I hope someday soon I'll get to be that again.

* And hey, I ain't ugly. Most guys would be lucky to age as well as I have, and dammit, I've got my good features. I mean, have you seen my hair? My hair is fucking fabulous. 

Life is short, and what's worse, you can never even be certain how short. Statistically I could have another 40 or 50 years left at least, but I've got the scars from too many brushes with death to take that for granted.

Don't you think, if life is so short, so precious, that the last thing we should waste our time doing is telling ourselves how shit we are? Sure a little introspection is valuable now and then, but come on. All this "humility" crap is for the birds. Own how great you are. Sit down sometime and really think hard and give yourself permission to do your own self-inventory, and remind yourself of what's great in your life. 

And if anyone has a problem with it? Fuck 'em. Let them marry the gaslighters of the world, while you're off having the time of your life.