= How do you say it?
:hp-tags: personal, politics

[.lead]
I cried this morning. 

I didn't know precisely why even, at the time. I was attempting moments before to look up options for our next meal on the internet. My wife stepped out on to the balcony, and while she was out there, I started weeping. 

After some time of this, when she had returned and asked me what was the matter, and I had managed to pull myself together enough to croak out a response, I said this:

"Everything is terrible."

My wife suggested that this was merely the depression talking. As Vonnegut might've said, my brain was producing bad chemicals again. 


[center]#\***#

The cat doesn't like me.

It's warming up again, I think, but very slowly. It still bolts from my presence if I try to offer it my hand. 

It wasn't always like this. When we first brought her home, I was the one to break the ice and pet the cat for the first time, eventually leading her to my wife. When my wife was out of town for a day the first week, the cat even came to me that night on the couch, and was brave enough to give me a kiss on the nose.

Then the next night, she was terrified of me, and ran from the room at every approach. 

I suspect the cat has suffered some trauma in her previous home. We purchased her from a woman with very Russian-inflected English who held her, or rather attempted to hold her, for the entire visit.

I have never in my life seen a cat that more clearly did not want to be where it was than at that moment. The woman gave us the hard sell, of course, telling us how it was her daughters (whom we've never met face to face), and how the daughter moved in with a boyfriend whose young male cat was mean to it. 

It didn't matter. From the moment I saw its face all I could think was "I've got to get this poor thing the hell out of here!" If I didn't, who would? What would happen to it? There was so much fear and discomfort in it. It needed to be rescued.

So we did. 

[center]#\***#

In my life time, there has never been a political party or leader or government in power which I can describe as properly left-wing.

In my home country, one has the choice between an obstructionist far-right party, and an ineffectual moderate-right party that inevitably makes a show of things but then caves to the demands of the former. Largely, this is because both parties take money in great quantities from the same very rich people, in order to fund their campaigns. So nothing ever changes on any meaningful level, it just gets worse, as the arms race for campaign expenditure only puts them more and more in the pockets of the very rich people. This is OK by them, however, because by and large most of them are very rich people themselves. 

America is a classist society at heart, which tells fairy tails of a classless one in order to keep the poor from complaining too much about the ruling class. And if they dare, they call them communists, or socialists, or anarchists, and send armed men to beat them up should they demonstrate in too great a number. 

That is the country I grew up in.

[center]#\***#

When I was in school, I had the most incredible social studies teacher. His name was Jim Erickson. He was of  Scandinavian descent, if I recall correctly, which perhaps goes to explain why he was the first and only teacher I ever had in my life to introduce me to the concept of democratic socialism.

I had another teacher, Mr. Hersch. He taught AP History, and his class was the first time I was 