= How to do things
:hp-tags: personal

A thread on HN asks, https://news.ycombinator.com/item?id=9936544["Why do you want to achieve something?"] This https://news.ycombinator.com/item?id=9939147[particular answer] struck a chord:

____
Honestly, it's the growing realization that despite all of my efforts, I haven't done anything worth feeling proud of. To me that feels like I've lived a waste of a life.

As you can tell, this is an ineffective strategy for motivation.
____


When I was a child, my parents and I once went down to see a guest preacher at the local church down in the canyon. It was the concluding event of a "vacation bible camp" I'd been attending on my parents'  wishes over the summer. I don't really remember the content of the speech he gave, other than that he was fond of audience participation, and at several points called upon random members of the audience to illustrate this point or that.

I was one of them.

That day, I had chosen to wear to church the jersey of the Chicago Cubs, the famously losing baseball team, who had not at that time won a World Series in something nearly like a century. I wasn't really a fan or anything, I didn't even like baseball, but someone had given it to me, and I liked wearing it because it was comfortable and cool in the summer time.

The preacher had evidently noticed the shirt, however, and at one point in his sermon chose to punctuate his point by singling me out of the crowd based entirely on my choice of clothing. He told me he felt sorry for anyone who was a Cubs fan, but admired my decision to stick with a losing team. For taking part as living prop to his point, or perhaps just for being a good sport and saying little of anything to interrupt it, he gave me a little plastic dinosaur egg, inside which I would later discover was some mediocre candy and a tiny rubberized plastic velociraptor. 

I just liked the shirt.

***

When I was 18, and what was left of my high school education was rapidly drawing to a close, my father came to me and told me he had an opportunity at work for me. The IT department at work was looking to hire a new employee, and I would be perfect for the job owing to the peculiar requirement that the IT department head had set on the hire.

The new boss was a man with a considerable amount of experience in the IT industry, and also who had a very particular way of doing things. Because of this, he quite specifically did not want to hire anyone who had any real work experience in the field, preferring instead a new body who would serve as a kind of apprentice. He could then train up a new employee to do exactly what he needed them to do, in the way that he needed them to do it, without having to "untrain" them from any method they might've picked up in their previous jobs.

He and my father had evidently discussed me as a serious candidate for the position, and felt that my hobby experience with computers would make me a perfect match. The job was more or less mine, all I had to do was say I wanted it, and I could be employed tomorrow. The pay was good, probably better from the start than any job I would wind up taking the rest of my life, and it came with benefits like health care and vacation which didn't seem especially important to me at the time but nowadays are worth their price alone. 

I turned it down.

I didn't want to have to stay living with my parents, out in Crooked River Ranch, which was so far away from anything like culture or human activity that for me it may as well have been the third moon of Rigel VII. Nor did I want to move to Madras, closer to where work was actually located, because it was and still is the asshole the tri-county area, essentially an entire city that had been turned into a ghetto for migrant workers from Mexico.

I said too, that I didn't think I wanted to work with computers for a living. That they were fine and fun as a hobby, but I was afraid I'd soon come not to enjoy dealing with them at all if I had to do anything with them for work. 

Sometimes I wonder if I was right ...

***

Nearly five years ago now, after reaching more or less the inescapable death of my cooking career, and being rejected by the United States Air Force on the basis of my poor credit history, I enrolled at  Central Oregon Community College in Bend, Oregon. I didn't really know what else I was going to do, so I though, well, maybe I should finally go back to school and learn how to do something that would pay me a living without having to be exchanged for a life of bone-battering toil.

College was a wonderful place. I felt like I was at home for the first time in a decade. I had incredible teachers and professors, who taught me about writing and literature and history, who gave me the chance to explore talents that had been all but neglected for the past third of my life. 

One of those professors was Cora Agatucci, an incredible old woman with a passion for film like no one I have ever met before. She was the kind of woman who would sigh dreamily at the thought of a good Truffaut shot, and her enthusiasm was almost viral. Almost no one, even the most slackoff of students, could manage to find no joy in her classrooms, and it was there that I rekindled a long neglected love of film. 

I decided, in fact, that I would make it my major, and even registered it as such with the admissions office. I made inquiries into what universities would be best for me to eventually transfer to in order to complete my degree, and learned of a promising new "cinema studies" program at the University of Oregon.

It was around this time, however, that an acquaintance of mine who worked in the film industry suggested instead that I should not waste my time with university, or even a degree. He said it wasn't necessary, and if I really wanted to get into film what I should do was just come down to California and he would help find me internships on film sets instead, where I could learn on the job.

I declined his offer. I said I wasn't really sure I wanted to live in California, and I as will still felt like I needed the qualification and credential a degree would give me. Indeed, at one point I'd more or less decided that I wanted to try and make a go of a film career without ever having to go anywhere near Los Angeles if I could help it, and in fact, harbored hopes of even studying abroad somehow instead. Maybe Vancouver, or France. 

***

Now comes the point in the piece where I would remind you again about that quote at the beginning, and tell you how I identified with it, how I was driven by guilt over my own lack of accomplishments. I would tell you the sob story of my father, who died aged 50 when I was only in my early 20s, having never seen me amount to anything but a regularly unemployed couchsurfer. I would tell you, perhaps even, if I truly wanted to bend the heartstrings, of hearing my father's words in the opening track of the last album my father ever listened to. "Carry On, my Wayward Son," it said. "There'll be peace when you are done."

It's a good story. I am sure that in the fullness of time I could spin up at least a few hundred words on that passage alone. The partial draft of this story even now buried within the technological wonder that is Git history.

It's also a lie.

Oh for sure, on some level I have for many years believed that lie. It took me some years to make piece with having been a living disappointment to my father, who had himself worked so hard for so many years to keep food on the table for my many siblings and I. In my head for many years I mad many plans and wishes and dreams for bigger and better things, as so many do.

And yet, by any honest accounting of my actions, year on year, I can find little evidence whatsoever that I have ever truly been driven to something even resembling success or achievement. A look at my history shows that I have repeatedly and deliberately managed to avoid it entirely.

No, I must instead say that my motives have far more often been that of the terminal care doctor, to be kept as "comfortable as possible."

I have avoided both risk and opportunity time after time, and all in the effort to simply be at least "tolerably uncomfortable," as that former draft said in perhaps its only self-honest words. I would pine for a time in which I was not poor, but cringed at the tasks before me that seemed my only routes out of it, or simply found no route at all. I have lacked the confidence or the drive to truly grab those things which I claimed to want and dream of, even when the only barrier to my achieving them was my own use of my time. 

Instead, I have simply sought to ensure there was good food in my belly, and something to keep me entertained as day passes after day. I embraced a policy of supreme relaxation, the end result of accidental Buddhism perhaps: I had lost so much and had so little over the years, that in the end I gave up on attachment simply as a matter of habit. What's the use of worry, of fear? What merit in torment?

And yet, through the years, that little lie still lived there, never quite silent. But guilt is a funny thing. It is, as the quoted said, not actually that effective of a motivator. It wallows. It festers. It condemns. But it seldom motivates. What better tool then, to enforce my self-imposed terminal patient status?

We are all, after all, terminal patients. Life is fatal, that much is certain. And so it is often the path of least resistance simply to keep oneself as comfortable as possible while one waits out their final hours, however long that might take. Why we do more than that is perhaps the mystery of the ages, certainly the animals seem to do little more than ensure their survival, content with just so.  

But I must thus advise, nevertheless, that should you truly wish to achieve, make sure of your motives. And if you find yourself becoming comfortable, get up and run. The secret of achievement is that the only way to achieve anything is just to do it, and the only way to get opportunity is to ask for it, or take it. 

Comfortable is the enemy of progress itself.