= Hocus Pocus - Excerpts from Chapter 32
:hp-tags: miscellaneous

“What a  clever trap your Ruling Class set for us,” he went on. “First the atomic bomb. Now this.”

“Trap?” I echoed wonderingly.

“They looted your public and corporate treasuries, and turned your industries over to nincompoops,” he said. “Then they had your Government borrow so heavily from us that we had no choice but to send over an Army of Occupation in business suits. Never before has the Ruling Class of a country found a way to stick other countries with all the responsibilities their wealth might imply, and still remain rich beyond the dreams of avarice! No wonder they thought the comatose Ronald Reagan was a great President!”

***

They had managed to convert their wealth, which had originally been in the form of factories or stores or other demanding enterprises, into a form so liquid and abstract, negotiable representations of money on paper, that there were few reminders coming from anywhere that they might be responsible for anyone outside their own circle of friends and relatives.
*They didn’t rage against the convicts. They were mad at the Government for not making sure that escapes from prison were impossible. The more they ran on like that, the clearer it became that it was their Government, not mine or the convicts’ or the Townies’. Its first duty, moreover, was to protect them from the lower classes, not only in this country but everywhere. 

***

If the Trustees were bad, the convicts were worse. I would be the last person to say otherwise. They were devastators of their own communities with gunfights and robberies and rapes, and the merchandising of brain-busting chemicals and on and on.

But at least they saw what they were doing, whereas people like the Trustees had a lot in common with B-52 bombardiers way up in the stratosphere. They seldom saw the devastation they caused as they moved the huge portion of this country’s wealth they controlled from here to there.

― Kurt Vonnegut, Hocus Pocus 

