= A Man Without a Country
:published_at: 2014-1-1
:hp-tags: politics, literature, personal

_Originally posted on https://ello.co/jarcane/post/kbS4tYC1SuSs5V4n05jz7A[ello]_

If you have even the slightest question about what book you should read next, the answer is that you should read Breakfast of Champions by Kurt Vonnegut. Probably even if you have already read it, except perhaps if you've read it very recently. If you have never read it, then you should absolutely read it from cover to cover, or at least listen to it via audiobook (there is an excellent recording with Stanley Tucci as narrator).

Breakfast of Champions was published in 1973.

And nearly every word of it is still true today in America, in 2015, 42 years later.

It is at times eerie to read or hear the words of Breakfast of Champions because of this fact. It is a work of both staggering brilliance in so much as it is absolutely incisive, insightful, and even prescient, yet it is also very nearly depressing because so much of that "prescience" is only because so little has really changed since 1973 once you scratch the surface.

In some ways, it has gotten worse. Kurt Vonnegut seemed to believe so, with his customary humor of course. In 2004, Vonnegut wrote that Kilgore Trout, the recurring protaganist, supporting cast member, and occasional hero of many of his books, had committed suicide on October 15th, 2004 by drinking Drano, as a result of being informed by a psychic that George W. Bush would be elected president for a second term.

He was.

Kurt Vonnegut himself went to his grave two years later. In the last book ever published while he was still alive, he had, like myself, given up on his country. Indeed, that was spelled out in the very title of the book, which echoes a https://www.goodreads.com/quotes/71604-in-case-you-haven-t-noticed-as-the-result-of-a[quote] from within: A Man Without a Country.

Kurt Vonnegut, was a very smart man. I think he was perhaps the greatest American writer since Mark Twain, and like Mark Twain, he had an utterly razor sharp gift for cutting through the bullshit of American culture and life.

Also like Mark Twain, in the end, he just couldn't put up with the bullshit anymore. And thus, A Man Without a Country, and his choice of "last words", which were these:

  "Life is no way to treat an animal, not even a mouse."

Mr. Vonnegut is gone now, and life can't treat him that way any more. The rest of us live on with what's left of this planet. At least I no longer must live on with what's left of the country we both were born into, yet no longer called our own. I too, am a man without a country.
