= Alone
:hp-tags: personal


When I was 13 years old I once predicted, and held for some time, that I would die by the age of 35. That deadline is just 8 months away. 

I am 34 years old.

34.

I was 31 years old before I had my first relationship. 

31 years old before the first, and so far only woman, to say "I love you" to me.

32 before my first proper kiss. 

32 before I first made love.


[quote]
____
"Some people, they are raised with a lot of love," she explains, "but some people are not. And these people who didn't get love in their childhood, when they meet a partner, they try to hold onto him like they own him. They think that this one person, they can only love him and he is the only one who will ever love them. And when they break up, the person feels like their life is over." Atsa thinks for a moment. "Maybe I am giving them a little love."
____


It is a standard piece of advice you will hear many times when you are single, and especially after a break-up or a divorce, that you must somehow become reaccustomed to being alone. "Just get comfortable being yourself again for a while."

With all due respect to all those well-meaning souls, try it for a few decades sometime and come back and tell me that again.

We human beings need love. We need it like we need air, or water, or food. 

We love to cling to pride and declare our independence, to declare that we stand alone, but no one truly does. 

And when that need is deprived, or warped, or broken and we stop believing that we can be loved, that is when we begin to walk a dark path. We cut ourselves off, from our emotions, from our humanity, from our fellow humans. We hurt ourselves. We hurt others. Sometimes, we can't even go on living. 


[quote]
____
The first assignment was to get into groups to brainstorm reasons that a person might commit suicide. The other boys in Paul-Ib's group messed around with a paper football. Paul-Ib bent over the paper and, in haphazard pencil, scribbled out 10 reasons. The first one said _Loneliness. Being lonely for long time. Being lonely in whole life._

Number three read simply _Love._
____


***

_Quotes from http://www.npr.org/sections/goatsandsoda/2016/04/21/474847921/the-arctic-suicides-its-not-the-dark-that-kills-you[The Arctic Suicides] by Rebecca Hersher_