= Alone
:hp-tags: personal


When I was 13 years old I once predicted, and held for some time, that I would die by the age of 35. That deadline is just 8 months away. 

I am 34 years old.

34.

I was 31 years old before I had my first relationship. 

31 years old before the first, and so far only woman, to say "I love you" to me.

32 before my first proper kiss. 

32 before I first made love.

It is a standard piece of advice you will hear many times when you are single, and especially after a break-up or a divorce, that you must somehow become reaccustomed to being alone. "Just get comfortable being yourself again for a while."

With all due respect to all those well-meaning souls, try it for a few decades sometime and come back and tell me that again.

We human beings need love. We need it like we need air, or water, or food. 

We love to cling to pride and declare our independence, to declare that we stand alone, but no one truly does. 

And when that need is deprived, or warped, or broken and we stop believing that we can be loved, that is when we begin to walk a dark path. We cut ourselves off, from our emotions, from our humanity, from our fellow humans. We hurt ourselves. We hurt others. Sometimes, we can't even go on living. 

Because that need, that urge to love and be loved, that is the root of all that is good in this world and the moment that you forget that, all bets are off. Love is the line between compassion and callousness. Without love

