= A Fairy Tale
:hp-tags: personal, writing

Once upon a time there was a boy, and he was afraid.

He was a small boy. A lonely boy.

He was not big and strong like some of the boys he knew, nor was he fast and agile, or handsome and strong. When a fight came to him, he knew that he would not win, and he lost many fights.

He lost fights against the other boys. He lost fights against his teachers. He lost fights against his parents. 

It hurt him to lose, made his heart ache, but it was not the pain of the bullies who struck him that hurt most, but the losing itself.

The boy felt as if he were nothing, as if he had no power at all, and because he had no power at all he saw little need for friends or other people, who had mostly only ever hurt him. Such was his fear of more hurt and pain that he shut himself away.

In time, it was as if the loneliness itself became his greatest friend. 

Instead of making friends with the others at school or in the neighborhood, the boy would while away the hours in his room, reading many books, playing games, writing and acting out stories that no one would ever read or see, and talking endlessly to no one at all but himself. 

His stories were endless and vivid things. Every toy in his room had its own personality, its own story, even its own rivalries with other toys. As the boy grew, so did the stories, and in those stories he found a new strength: imagination.

