= Alone
:hp-tags: personal


When I was 13 years old I once predicted, and held for some time, that I would die by the age of 35. That deadline is just 8 months away. 

I am 34 years old.

34.

I was 31 years old before I had my first relationship. 

31 years old before the first, and so far only woman, to say "I love you" to me.

32 before my first proper kiss. 

32 before I first made love.


[quote, The Arctic Suicides]
____
"Some people, they are raised with a lot of love," she explains, "but some people are not. And these people who didn't get love in their childhood, when they meet a partner, they try to hold onto him like they own him. They think that this one person, they can only love him and he is the only one who will ever love them. And when they break up, the person feels like their life is over." Atsa thinks for a moment. "Maybe I am giving them a little love."
____


It is a standard piece of advice you will hear many times when you are single, and especially after a break-up or a divorce, that you must somehow become accustomed to being alone before you can proceed to find love. "Just get comfortable being yourself for a while."

With all due respect to all those well-meaning souls, I recommend you try it for a couple decades sometime before you consider passing on that advice a second time.

We human beings need love. We need it like we need air, or water, or food. 

We love to cling to pride and declare our independence, to declare that we stand alone, but no one truly does. 

And when that need is deprived, or warped, or broken and we stop believing that we can be loved, that is when we begin to walk a dark path. We cut ourselves off, from our emotions, from our humanity, from our fellow humans. We hurt ourselves. We hurt others. Sometimes, we can't even go on living. 


[quote, The Arctic Suicides]
____
The first assignment was to get into groups to brainstorm reasons that a person might commit suicide. The other boys in Paul-Ib's group messed around with a paper football. Paul-Ib bent over the paper and, in haphazard pencil, scribbled out 10 reasons. The first one said _Loneliness. Being lonely for long time. Being lonely in whole life._

Number three read simply _Love._
____


I have found it difficult to describe to someone what it is even like to be so long without it. People do not believe it. 

Those same people who will tell you with great air of wisdom and authority of the importance of coming to terms with being alone will look in abject disbelief and respond with blank platitudes when I tell them that, for instance, every single romantic pursuit in my 34 years on this planet has ended in heartbreak.

The very notion of what that might feel like seems to so terrify them that the flee into cliche rather than confront the thought. 

I do not judge them for it. I fled myself, in a way. I knew from a very early age that what I wanted more than anything in this world was love, and when more than a decade of my life came and went with only one disappointment and loss after another, I simply gave up for another decade. 

I sank into nothingness. 10 years or more of my life simply vanished with no consequence, as I simply grew accustomed only to surviving and finding ways to keep myself entertained as I waited out existence. I had few friends that were not digital, I achieved nothing of any note, my career slowly spiraled towards the drain. 

I was simply waiting to die, and prepared for however long that would take.

Then one day I nearly did. I stared death in the face, screaming and afraid, and to my surprise, I fought it. 

For four days and five nights I fought it, and somehow, I won.

When I came out the other side, I found what had been keeping me alive: I still wanted love. And I was damned if I was going to die before I found it.

Now, here on the other side of one of the greatest chances I have ever taken in my life, a chance I took ultimately in hopes I had found it, I once again found myself facing that same realization.


[quote, Jim Butcher, Dead Beat]
____
“Son. Everyone dies alone. That's what it is. It's a door. It's one person wide. When you go through it, you do it alone. But it doesn't mean you've got to be alone before you go through the door. And believe me, you aren't alone on the other side.” 
____



***

_Quotes from http://www.npr.org/sections/goatsandsoda/2016/04/21/474847921/the-arctic-suicides-its-not-the-dark-that-kills-you[The Arctic Suicides] by Rebecca Hersher, except where otherwise indicated_