= A Fairy Tale
:hp-tags: personal, writing

Once upon a time there was a boy, and he was afraid.

He was a small boy. A lonely boy.

He was not big and strong like some of the boys he knew, nor was he fast and agile, or handsome and charming. When a fight came to him, he knew that he would not win, and he lost many fights.

He lost fights against the other boys. He lost fights against his teachers. He lost fights against his parents. 

It hurt him to lose, made his heart ache, but it was not the pain of the bullies who struck him that hurt most, but the losing itself.

The boy felt as if he were nothing, as if he had no power at all, and because he had no power at all he saw little need for friends or other people, who had mostly only ever hurt him. Such was his fear of more hurt and pain that he shut himself away.

In time, it was as if the loneliness itself became his greatest friend. 

Instead of making friends with the others at school or in the neighborhood, the boy would while away the hours in his room, reading many books, playing games, writing and acting out stories that no one would ever read or see, and talking endlessly to no one at all but himself. 

His stories were endless and vivid things. Every toy in his room had its own personality, its own story, even its own rivalries with other toys. As the boy grew, so did the stories, and in those stories he was not a frail, powerless thing, but instead could be anything his heart desired. He could be a powerful warrior, a cunning strategist, an unfailingly clever orator. In his stories, he needed to fear only that kind of fear that was just enough to motivate the hero to fight, and to win.

Then one night as he slept, a monster came. 

It was a powerful monster, as real and as terrifying as anything he had ever faced in the school halls or the playground. For as his gift for stories grew, so too had his dreams, which had become so powerful and vivid that they were as if he were walking through a movie set, and now the fears that once only had tormented him in life threatened to take away his sleep.

He awoke with a start, afraid, but what was new, angry. This time, he would not go down without a fight. For what is a dream but a story that plays out in our minds at night, and he knew stories all too well.

And so in the dead of night, he took an old box and cut from it a sword, and on that sword he drew strange runes and symbols whose meaning was known only as they came to him. And as he tucked himself in to sleep he clutched the grip of his little paper sword and drifted off into dreams.

This time, he was ready, and when the monster came he called to memory that sword and its runes. As he imagined it, the sword came to life in his hands, not simple paper, but cold steel and razor sharp, and with the sword he slew the monster dead. No longer would he fear the night, so long as he held his paper sword. 

