= We can be heroes
:hp-tags: personal

video::bsYp9q3QNaQ[youtube]

On the 10th of January, 2016, David Bowie left this Earth a blander place. 

There are people who walk this earth so long, and with such power over our hearts, that we never believe they will truly leave.

When a man of Bowie's legend leaves it, it reminds us all that no one is truly immortal except by what they leave behind.

And it is in that moment that we feel afraid, and we feel lost, and we feel powerless. If a man like him can fall, what of us?

I chose this song to head this post because he was one of mine. Though I did not follow his life, what I followed and admired since I was a young man was the icon, the music, the face. As an odd, thin, bicurious young man struggling with his place in the world, nothing ever inspired me more than knowing there was someone like him out there daring anyone in the world to deny him the right to be all that and so much more.

"We can be heroes, just for one day," he sings. "We can beat them, just for one day."

Some days, that's all the hope you need. All the reason you need to reach for love, for courage, to be who you truly wish to be. That we can find our happiness, if just for one day. 

"Oh we can beat them, for ever and ever."

Thank you, David. For everything.